version: '2'

services:
  datafusion-app:
    build:
      context: ./datafusion
    image: myapp/datafusion-app:latest
    container_name: datafusion-app
    ports:
      - "8501:8501"
      - "4040:4040"
    environment:
      SPARK_UI_PORT: 4040
    volumes:
      - ./datafusion:/app
    depends_on:
      - rk-kafka

  rk-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: rk-zookeeper
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  rk-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: rk-kafka
    depends_on:
      - rk-zookeeper
    ports:
      - "9093:9093"       # External access (host -> Kafka)
      - "29093:29093"     # Internal access (other containers -> Kafka)
    volumes:
      - streaming_data:/data:rw
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: rk-zookeeper:2182
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://rk-kafka:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "raw:1:1"

volumes:
  streaming_data:
